name: supmap_clean
description: New Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.2
  flutter_appauth: ^9.0.1
  flutter_secure_storage: ^9.2.4
  path_provider: ^2.1.5
  google_maps_flutter: ^2.10.1
  auth0_flutter: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
